-- MySQL Script generated by MySQL Workbench
-- Mon Sep 15 01:55:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `customername` VARCHAR(16) NOT NULL,
  `gender` VARCHAR(16) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `telphone` INT NOT NULL,
  `Membershiplevel` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `telphone_UNIQUE` (`telphone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pets` (
  `petID` INT NOT NULL AUTO_INCREMENT,
  `customers_customerID` INT NOT NULL,
  `petname` VARCHAR(45) NOT NULL,
  `pet_species` VARCHAR(45) NOT NULL,
  `pet_breeds` VARCHAR(45) NOT NULL,
  `pet_gender` VARCHAR(45) NOT NULL,
  `pet_age` INT NOT NULL,
  `neuter` VARCHAR(45) NULL,
  `pet_character` VARCHAR(45) NULL,
  PRIMARY KEY (`petID`),
  INDEX `fk_pets_customers1_idx` (`customers_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_pets_customers1`
    FOREIGN KEY (`customers_customerID`)
    REFERENCES `mydb`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`classify_level1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classify_level1` (
  `classify1_ID` INT NOT NULL AUTO_INCREMENT,
  `parentID` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`classify1_ID`),
  INDEX `parentID_idx` (`parentID` ASC) INVISIBLE,
  CONSTRAINT `parentID`
    FOREIGN KEY (`parentID`)
    REFERENCES `mydb`.`classify_level1` (`classify1_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brandID` INT NOT NULL,
  `brandname` VARCHAR(45) NULL,
  PRIMARY KEY (`brandID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `classify_level1_classify1_ID` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_baozhiqi` INT NOT NULL,
  `local` VARCHAR(45) NULL,
  `brand_brandID` INT NOT NULL,
  PRIMARY KEY (`productID`),
  INDEX `fk_product_classify_level11_idx` (`classify_level1_classify1_ID` ASC) VISIBLE,
  INDEX `fk_product_brand1_idx` (`brand_brandID` ASC) VISIBLE,
  CONSTRAINT `fk_product_classify_level11`
    FOREIGN KEY (`classify_level1_classify1_ID`)
    REFERENCES `mydb`.`classify_level1` (`classify1_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `mydb`.`brand` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dealer` (
  `dealerID` INT NOT NULL,
  `dealer_name` VARCHAR(45) NULL,
  `dealer_tel` INT NULL,
  `dealer_address` VARCHAR(45) NULL,
  PRIMARY KEY (`dealerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`stock_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_in` (
  `stock_inID` INT NOT NULL AUTO_INCREMENT,
  `stock_in_date` DATETIME NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `dealer_dealerID` INT NOT NULL,
  PRIMARY KEY (`stock_inID`),
  INDEX `fk_stock_in_dealer1_idx` (`dealer_dealerID` ASC) VISIBLE,
  CONSTRAINT `fk_stock_in_dealer1`
    FOREIGN KEY (`dealer_dealerID`)
    REFERENCES `mydb`.`dealer` (`dealerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`spec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spec` (
  `specID` INT NOT NULL,
  `product_productID` INT NOT NULL,
  `spec_name` VARCHAR(45) NOT NULL,
  `spec_value` VARCHAR(45) NOT NULL,
  `barcode` INT NULL,
  `picture` VARCHAR(45) NULL,
  `总库存` INT NULL,
  PRIMARY KEY (`specID`),
  INDEX `fk_spec_detail_product1_idx` (`product_productID` ASC) VISIBLE,
  CONSTRAINT `fk_spec_detail_product1`
    FOREIGN KEY (`product_productID`)
    REFERENCES `mydb`.`product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`stock_in_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_in_detail` (
  `stock_in_detail` INT NOT NULL,
  `stock_inID` INT NOT NULL,
  `spec_specID` INT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `price_in` INT NOT NULL,
  `product_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`stock_in_detail`),
  INDEX `fk_stock_in_detail_stock_in1_idx` (`stock_inID` ASC) VISIBLE,
  INDEX `fk_stock_in_detail_spec1_idx` (`spec_specID` ASC) VISIBLE,
  CONSTRAINT `fk_stock_in_detail_stock_in1`
    FOREIGN KEY (`stock_inID`)
    REFERENCES `mydb`.`stock_in` (`stock_inID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_in_detail_spec1`
    FOREIGN KEY (`spec_specID`)
    REFERENCES `mydb`.`spec` (`specID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`brand_has_dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand_has_dealer` (
  `brand_brandID` INT NOT NULL,
  `dealer_dealerID` INT NOT NULL,
  PRIMARY KEY (`brand_brandID`, `dealer_dealerID`),
  INDEX `fk_brand_has_dealer_dealer1_idx` (`dealer_dealerID` ASC) VISIBLE,
  INDEX `fk_brand_has_dealer_brand1_idx` (`brand_brandID` ASC) VISIBLE,
  CONSTRAINT `fk_brand_has_dealer_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `mydb`.`brand` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brand_has_dealer_dealer1`
    FOREIGN KEY (`dealer_dealerID`)
    REFERENCES `mydb`.`dealer` (`dealerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `customers_customerID` INT NOT NULL,
  `price` INT NULL,
  `discount` INT NULL,
  `sale_time` DATETIME NULL,
  `pay_way` VARCHAR(45) NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_order_customers1_idx` (`customers_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_order_customers1`
    FOREIGN KEY (`customers_customerID`)
    REFERENCES `mydb`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_deatil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_deatil` (
  `order_deatilID` INT NOT NULL AUTO_INCREMENT,
  `order_orderID` INT NOT NULL,
  `spec_specID` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_deatilID`, `order_orderID`),
  INDEX `fk_order_deatil_order1_idx` (`order_orderID` ASC) VISIBLE,
  INDEX `fk_order_deatil_spec1_idx` (`spec_specID` ASC) VISIBLE,
  CONSTRAINT `fk_order_deatil_order1`
    FOREIGN KEY (`order_orderID`)
    REFERENCES `mydb`.`order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_deatil_spec1`
    FOREIGN KEY (`spec_specID`)
    REFERENCES `mydb`.`spec` (`specID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- 创建服务项目表
CREATE TABLE `services` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(100) NOT NULL,
  `description` TEXT,
  `duration` INT NOT NULL COMMENT '分钟',
  `price` DECIMAL(10,2) NOT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 创建预约表
CREATE TABLE `appointments` (
  `appointment_id` INT NOT NULL AUTO_INCREMENT,
  `customerid` INT NOT NULL,
  `petid` INT NOT NULL,
  `service_id` INT NOT NULL,
  `appointment_date` DATE NOT NULL,
  `appointment_time` TIME NOT NULL,
  `status` ENUM('待确认', '已确认', '已完成', '已取消') NOT NULL DEFAULT '待确认',
  `notes` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`appointment_id`),
  FOREIGN KEY (`customerid`) REFERENCES `customers`(`customerid`),
  FOREIGN KEY (`petid`) REFERENCES `pets`(`petid`),
  FOREIGN KEY (`service_id`) REFERENCES `services`(`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


USE `mydb`;
-- 插入分类数据
INSERT INTO classify_level1 (classify1_ID, parentID, name) VALUES
(1, NULL, '宠物食品'),
(2, NULL, '宠物用品'),
(3, 1, '狗粮'),
(4, 1, '猫粮'),
(5, 2, '玩具'),
(6, 2, '清洁用品');

-- 插入品牌数据
INSERT INTO brand (brandID, brandname) VALUES
(1, '皇家'),
(2, '宝路'),
(3, '雀巢'),
(4, '宠物之家'),
(5, '爱宠');

-- 插入产品数据
INSERT INTO product (productID, classify_level1_classify1_ID, product_name, product_baozhiqi, local, brand_brandID) VALUES
(1, 3, '皇家小型犬成犬粮', 12, '法国', 1),
(2, 3, '宝路牛肉味狗粮', 18, '中国', 2),
(3, 4, '雀冠猫粮', 24, '美国', 3),
(4, 5, '宠物玩具球', 36, '中国', 4),
(5, 6, '宠物沐浴露', 24, '日本', 5);

-- 插入规格数据
INSERT INTO spec (specID, product_productID, spec_name, spec_value, barcode, picture, 总库存) VALUES
(1, 1, '重量', '3kg', 100001, 'royal_3kg.jpg', 50),
(2, 1, '重量', '10kg', 100002, 'royal_10kg.jpg', 30),
(3, 2, '重量', '2kg', 100003, 'pedigree_2kg.jpg', 40),
(4, 3, '重量', '5kg', 100004, 'purina_5kg.jpg', 25),
(5, 4, '尺寸', '中号', 100005, 'toy_ball_m.jpg', 100),
(6, 5, '容量', '500ml', 100006, 'shampoo_500ml.jpg', 60);

-- 插入经销商数据
INSERT INTO dealer (dealerID, dealer_name, dealer_tel, dealer_address) VALUES
(1, '北京宠物用品批发', 1380013800, '北京市朝阳区'),
(2, '上海宠物食品公司', 1390013900, '上海市浦东新区'),
(3, '广州宠物用品中心', 1370013700, '广州市天河区');

-- 插入品牌经销商关系
INSERT INTO brand_has_dealer (brand_brandID, dealer_dealerID) VALUES
(1, 1),
(1, 2),
(2, 1),
(3, 2),
(4, 3),
(5, 3);

-- 插入入库单数据
INSERT INTO stock_in (stock_inID, stock_in_date, total_amount, dealer_dealerID) VALUES
(1, '2024-01-15 10:00:00', 5000.00, 1),
(2, '2024-01-20 14:30:00', 8000.00, 2),
(3, '2024-02-01 09:15:00', 3000.00, 3);

-- 插入入库明细数据
INSERT INTO stock_in_detail (stock_in_detail, stock_inID, spec_specID, quantity, price_in, product_date) VALUES
(1, 1, 1, '20', 200, '2024-06-01'),
(2, 1, 2, '10', 180, '2024-05-15'),
(3, 2, 3, '30', 150, '2024-07-01'),
(4, 2, 4, '15', 220, '2024-06-20'),
(5, 3, 5, '50', 30, '2024-08-01'),
(6, 3, 6, '40', 45, '2024-07-15');
