-- MySQL Script generated by MySQL Workbench
-- Mon Sep 15 01:55:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- 修复版本 - 解决商品创建500错误

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `customername` VARCHAR(16) NOT NULL,
  `gender` VARCHAR(16) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `telphone` INT NOT NULL,
  `Membershiplevel` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `telphone_UNIQUE` (`telphone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pets` (
  `petID` INT NOT NULL AUTO_INCREMENT,
  `customers_customerID` INT NOT NULL,
  `petname` VARCHAR(45) NOT NULL,
  `pet_species` VARCHAR(45) NOT NULL,
  `pet_breeds` VARCHAR(45) NOT NULL,
  `pet_gender` VARCHAR(45) NOT NULL,
  `pet_age` INT NOT NULL,
  `neuter` VARCHAR(45) NULL,
  `pet_character` VARCHAR(45) NULL,
  `pet_image` VARCHAR(255) NULL COMMENT '宠物图片',
  PRIMARY KEY (`petID`),
  INDEX `fk_pets_customers1_idx` (`customers_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_pets_customers1`
    FOREIGN KEY (`customers_customerID`)
    REFERENCES `mydb`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classify_level1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classify_level1` (
  `classify1_ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `parentID` INT NULL,
  PRIMARY KEY (`classify1_ID`),
  INDEX `fk_classify_level1_classify_level1_idx` (`parentID` ASC) VISIBLE,
  CONSTRAINT `fk_classify_level1_classify_level1`
    FOREIGN KEY (`parentID`)
    REFERENCES `mydb`.`classify_level1` (`classify1_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brandID` INT NOT NULL,
  `brandname` VARCHAR(45) NULL,
  PRIMARY KEY (`brandID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `classify_level1_classify1_ID` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_baozhiqi` INT NULL COMMENT '保质期（月），可为空',
  `local` VARCHAR(45) NULL,
  `cover_image` VARCHAR(255) NULL COMMENT '商品封面图片',
  `brand_brandID` INT NOT NULL,
  PRIMARY KEY (`productID`),
  INDEX `fk_product_classify_level11_idx` (`classify_level1_classify1_ID` ASC) VISIBLE,
  INDEX `fk_product_brand1_idx` (`brand_brandID` ASC) VISIBLE,
  INDEX `idx_product_brand` (`brand_brandID` ASC) VISIBLE,
  INDEX `idx_product_classify` (`classify_level1_classify1_ID` ASC) VISIBLE,
  CONSTRAINT `fk_product_classify_level11`
    FOREIGN KEY (`classify_level1_classify1_ID`)
    REFERENCES `mydb`.`classify_level1` (`classify1_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `mydb`.`brand` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`spec_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spec_type` (
  `spec_type_id` INT NOT NULL AUTO_INCREMENT,
  `spec_name` VARCHAR(100) NOT NULL,
  `unit` VARCHAR(20) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`spec_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dealer` (
  `dealerID` INT NOT NULL,
  `dealer_name` VARCHAR(45) NULL,
  `dealer_tel` INT NULL,
  `dealer_address` VARCHAR(45) NULL,
  PRIMARY KEY (`dealerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`stock_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_in` (
  `stock_inID` INT NOT NULL AUTO_INCREMENT,
  `stock_in_date` DATETIME NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `dealer_dealerID` INT NOT NULL,
  PRIMARY KEY (`stock_inID`),
  INDEX `fk_stock_in_dealer1_idx` (`dealer_dealerID` ASC) VISIBLE,
  CONSTRAINT `fk_stock_in_dealer1`
    FOREIGN KEY (`dealer_dealerID`)
    REFERENCES `mydb`.`dealer` (`dealerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`spec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spec` (
  `specID` INT NOT NULL,
  `product_productID` INT NOT NULL,
  `spec_type_id` INT NULL COMMENT '规格类型ID，可为空',
  `spec_name` VARCHAR(45) NULL COMMENT '规格名称，可为空',
  `spec_value` VARCHAR(45) NULL COMMENT '规格值，可为空',
  `barcode` VARCHAR(50) NULL COMMENT '条形码，可为空',
  `picture` VARCHAR(255) NULL COMMENT '规格图片，可为空',
  `总库存` INT NULL DEFAULT 0 COMMENT '总库存，可为空，默认为0',
  `unit` VARCHAR(20) NULL COMMENT '单位',
  PRIMARY KEY (`specID`),
  INDEX `fk_spec_detail_product1_idx` (`product_productID` ASC) VISIBLE,
  INDEX `fk_spec_spec_type_idx` (`spec_type_id` ASC) VISIBLE,
  INDEX `idx_spec_barcode` (`barcode` ASC) VISIBLE,
  INDEX `idx_spec_product` (`product_productID` ASC) VISIBLE,
  CONSTRAINT `fk_spec_detail_product1`
    FOREIGN KEY (`product_productID`)
    REFERENCES `mydb`.`product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spec_spec_type`
    FOREIGN KEY (`spec_type_id`)
    REFERENCES `mydb`.`spec_type` (`spec_type_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`stock_in_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_in_detail` (
  `stock_in_detail` INT NOT NULL,
  `stock_inID` INT NOT NULL,
  `spec_specID` INT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `price_in` INT NOT NULL,
  `product_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`stock_in_detail`),
  INDEX `fk_stock_in_detail_stock_in1_idx` (`stock_inID` ASC) VISIBLE,
  INDEX `fk_stock_in_detail_spec1_idx` (`spec_specID` ASC) VISIBLE,
  CONSTRAINT `fk_stock_in_detail_stock_in1`
    FOREIGN KEY (`stock_inID`)
    REFERENCES `mydb`.`stock_in` (`stock_inID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_in_detail_spec1`
    FOREIGN KEY (`spec_specID`)
    REFERENCES `mydb`.`spec` (`specID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`brand_has_dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand_has_dealer` (
  `brand_brandID` INT NOT NULL,
  `dealer_dealerID` INT NOT NULL,
  PRIMARY KEY (`brand_brandID`, `dealer_dealerID`),
  INDEX `fk_brand_has_dealer_dealer1_idx` (`dealer_dealerID` ASC) VISIBLE,
  INDEX `fk_brand_has_dealer_brand1_idx` (`brand_brandID` ASC) VISIBLE,
  CONSTRAINT `fk_brand_has_dealer_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `mydb`.`brand` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brand_has_dealer_dealer1`
    FOREIGN KEY (`dealer_dealerID`)
    REFERENCES `mydb`.`dealer` (`dealerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `customers_customerID` INT NOT NULL,
  `price` INT NULL,
  `discount` INT NULL,
  `sale_time` DATETIME NULL,
  `pay_way` VARCHAR(45) NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_order_customers1_idx` (`customers_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_order_customers1`
    FOREIGN KEY (`customers_customerID`)
    REFERENCES `mydb`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_deatil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_deatil` (
  `order_deatilID` INT NOT NULL AUTO_INCREMENT,
  `order_orderID` INT NOT NULL,
  `spec_specID` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_deatilID`, `order_orderID`),
  INDEX `fk_order_deatil_order1_idx` (`order_orderID` ASC) VISIBLE,
  INDEX `fk_order_deatil_spec1_idx` (`spec_specID` ASC) VISIBLE,
  CONSTRAINT `fk_order_deatil_order1`
    FOREIGN KEY (`order_orderID`)
    REFERENCES `mydb`.`order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_deatil_spec1`
    FOREIGN KEY (`spec_specID`)
    REFERENCES `mydb`.`spec` (`specID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- 创建服务项目表
CREATE TABLE `services` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(100) NOT NULL,
  `description` TEXT,
  `duration` INT NOT NULL COMMENT '分钟',
  `price` DECIMAL(10,2) NOT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 创建预约表
CREATE TABLE `appointments` (
  `appointment_id` INT NOT NULL AUTO_INCREMENT,
  `customerid` INT NOT NULL,
  `petid` INT NOT NULL,
  `service_id` INT NOT NULL,
  `appointment_date` DATE NOT NULL,
  `appointment_time` TIME NOT NULL,
  `status` ENUM('待确认', '已确认', '已完成', '已取消') NOT NULL DEFAULT '待确认',
  `notes` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`appointment_id`),
  FOREIGN KEY (`customerid`) REFERENCES `customers`(`customerID`),
  FOREIGN KEY (`petid`) REFERENCES `pets`(`petID`),
  FOREIGN KEY (`service_id`) REFERENCES `services`(`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 插入默认数据
INSERT IGNORE INTO `spec_type` (`spec_type_id`, `spec_name`, `unit`, `description`) 
VALUES (1, '默认规格', '', '系统默认规格类型');

-- 插入示例品牌数据
INSERT IGNORE INTO `brand` (`brandID`, `brandname`) VALUES 
(1, '示例品牌1'),
(2, '示例品牌2'),
(3, '示例品牌3');

-- 插入示例分类数据
INSERT IGNORE INTO `classify_level1` (`classify1_ID`, `name`, `parentID`) VALUES 
(1, '宠物用品', NULL),
(2, '食品', 1),
(3, '玩具', 1),
(4, '护理用品', 1);

-- 插入示例经销商数据
INSERT IGNORE INTO `dealer` (`dealerID`, `dealer_name`, `dealer_tel`, `dealer_address`) VALUES 
(1, '示例经销商1', 1234567890, '示例地址1'),
(2, '示例经销商2', 1234567891, '示例地址2');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
