-- MySQL Script generated by MySQL Workbench
-- Mon Sep 15 01:55:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `customername` VARCHAR(16) NOT NULL,
  `gender` VARCHAR(16) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `telphone` INT NOT NULL,
  `Membership level` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `telphone_UNIQUE` (`telphone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pets` (
  `petID` INT NOT NULL AUTO_INCREMENT,
  `customers_customerID` INT NOT NULL,
  `petname` VARCHAR(45) NOT NULL,
  `pet_species` VARCHAR(45) NOT NULL,
  `pet_breeds` VARCHAR(45) NOT NULL,
  `pet_gender` VARCHAR(45) NOT NULL,
  `pet_age` INT NOT NULL,
  `neuter` VARCHAR(45) NULL,
  `pet_character` VARCHAR(45) NULL,
  PRIMARY KEY (`petID`),
  INDEX `fk_pets_customers1_idx` (`customers_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_pets_customers1`
    FOREIGN KEY (`customers_customerID`)
    REFERENCES `mydb`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`classify_level1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classify_level1` (
  `classify1_ID` INT NOT NULL AUTO_INCREMENT,
  `parentID` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`classify1_ID`),
  INDEX `parentID_idx` (`parentID` ASC) INVISIBLE,
  CONSTRAINT `parentID`
    FOREIGN KEY (`parentID`)
    REFERENCES `mydb`.`classify_level1` (`classify1_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brandID` INT NOT NULL,
  `brandname` VARCHAR(45) NULL,
  PRIMARY KEY (`brandID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `classify_level1_classify1_ID` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_baozhiqi` INT NOT NULL,
  `local` VARCHAR(45) NULL,
  `brand_brandID` INT NOT NULL,
  PRIMARY KEY (`productID`),
  INDEX `fk_product_classify_level11_idx` (`classify_level1_classify1_ID` ASC) VISIBLE,
  INDEX `fk_product_brand1_idx` (`brand_brandID` ASC) VISIBLE,
  CONSTRAINT `fk_product_classify_level11`
    FOREIGN KEY (`classify_level1_classify1_ID`)
    REFERENCES `mydb`.`classify_level1` (`classify1_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `mydb`.`brand` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dealer` (
  `dealerID` INT NOT NULL,
  `dealer_name` VARCHAR(45) NULL,
  `dealer_tel` INT NULL,
  `dealer_address` VARCHAR(45) NULL,
  PRIMARY KEY (`dealerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`stock_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_in` (
  `stock_inID` INT NOT NULL AUTO_INCREMENT,
  `stock_in_date` DATETIME NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `dealer_dealerID` INT NOT NULL,
  PRIMARY KEY (`stock_inID`),
  INDEX `fk_stock_in_dealer1_idx` (`dealer_dealerID` ASC) VISIBLE,
  CONSTRAINT `fk_stock_in_dealer1`
    FOREIGN KEY (`dealer_dealerID`)
    REFERENCES `mydb`.`dealer` (`dealerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`spec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spec` (
  `specID` INT NOT NULL,
  `product_productID` INT NOT NULL,
  `spec_name` VARCHAR(45) NOT NULL,
  `spec_value` VARCHAR(45) NOT NULL,
  `barcode` INT NULL,
  `picture` VARCHAR(45) NULL,
  `总库存` INT NULL,
  PRIMARY KEY (`specID`, `product_productID`),
  INDEX `fk_spec_detail_product1_idx` (`product_productID` ASC) VISIBLE,
  CONSTRAINT `fk_spec_detail_product1`
    FOREIGN KEY (`product_productID`)
    REFERENCES `mydb`.`product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`stock_in_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_in_detail` (
  `stock_in_detail` INT NOT NULL,
  `stock_inID` INT NOT NULL,
  `spec_specID` INT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `price_in` INT NOT NULL,
  `product_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`stock_in_detail`, `stock_inID`),
  INDEX `fk_stock_in_detail_stock_in1_idx` (`stock_inID` ASC) VISIBLE,
  INDEX `fk_stock_in_detail_spec1_idx` (`spec_specID` ASC) VISIBLE,
  CONSTRAINT `fk_stock_in_detail_stock_in1`
    FOREIGN KEY (`stock_inID`)
    REFERENCES `mydb`.`stock_in` (`stock_inID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_in_detail_spec1`
    FOREIGN KEY (`spec_specID`)
    REFERENCES `mydb`.`spec` (`specID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`brand_has_dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand_has_dealer` (
  `brand_brandID` INT NOT NULL,
  `dealer_dealerID` INT NOT NULL,
  PRIMARY KEY (`brand_brandID`, `dealer_dealerID`),
  INDEX `fk_brand_has_dealer_dealer1_idx` (`dealer_dealerID` ASC) VISIBLE,
  INDEX `fk_brand_has_dealer_brand1_idx` (`brand_brandID` ASC) VISIBLE,
  CONSTRAINT `fk_brand_has_dealer_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `mydb`.`brand` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brand_has_dealer_dealer1`
    FOREIGN KEY (`dealer_dealerID`)
    REFERENCES `mydb`.`dealer` (`dealerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `customers_customerID` INT NOT NULL,
  `price` INT NULL,
  `discount` INT NULL,
  `sale_time` DATETIME NULL,
  `pay_way` VARCHAR(45) NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_order_customers1_idx` (`customers_customerID` ASC) VISIBLE,
  CONSTRAINT `fk_order_customers1`
    FOREIGN KEY (`customers_customerID`)
    REFERENCES `mydb`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_deatil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_deatil` (
  `order_deatilID` INT NOT NULL AUTO_INCREMENT,
  `order_orderID` INT NOT NULL,
  `spec_specID` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_deatilID`, `order_orderID`),
  INDEX `fk_order_deatil_order1_idx` (`order_orderID` ASC) VISIBLE,
  INDEX `fk_order_deatil_spec1_idx` (`spec_specID` ASC) VISIBLE,
  CONSTRAINT `fk_order_deatil_order1`
    FOREIGN KEY (`order_orderID`)
    REFERENCES `mydb`.`order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_deatil_spec1`
    FOREIGN KEY (`spec_specID`)
    REFERENCES `mydb`.`spec` (`specID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
