-- MySQL Script generated by MySQL Workbench
-- Final version with all fixes for product creation issues
-- Model: New Model    Version: 4.0
-- 修复商品创建500错误的最终版本

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customername` VARCHAR(16) NOT NULL,
  `gender` VARCHAR(16) NOT NULL,
  `address` VARCHAR(255) NOT NULL DEFAULT '未知地址',
  `telphone` VARCHAR(20) NOT NULL,
  `Membershiplevel` INT NOT NULL DEFAULT 1,
  `membership_balance` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '会员余额',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `telphone_UNIQUE` (`telphone` ASC) VISIBLE,
  INDEX `idx_customers_phone` (`telphone` ASC) VISIBLE,
  INDEX `idx_customers_membership` (`Membershiplevel` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pets` (
  `pet_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `petname` VARCHAR(45) NOT NULL,
  `pet_species` VARCHAR(45) NOT NULL,
  `pet_breeds` VARCHAR(45) NOT NULL,
  `pet_gender` VARCHAR(45) NOT NULL,
  `pet_age` INT NOT NULL DEFAULT 0,
  `neuter` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否已绝育',
  `pet_character` VARCHAR(45) NULL,
  `pet_image` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '宠物图片URL',
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pets_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `idx_pets_customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `idx_pets_species` (`pet_species` ASC) VISIBLE,
  CONSTRAINT `fk_pets_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`membership_recharge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membership_recharge` (
  `recharge_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `recharge_amount` DECIMAL(10,2) NOT NULL COMMENT '充值金额',
  `bonus_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '赠送金额',
  `recharge_time` DATETIME NOT NULL COMMENT '充值时间',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`recharge_id`),
  INDEX `idx_customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `idx_recharge_time` (`recharge_time` ASC) VISIBLE,
  CONSTRAINT `fk_membership_recharge_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`classify_level1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classify_level1` (
  `classify1_ID` INT NOT NULL AUTO_INCREMENT,
  `parentID` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`classify1_ID`),
  INDEX `parentID_idx` (`parentID` ASC) INVISIBLE,
  CONSTRAINT `parentID`
    FOREIGN KEY (`parentID`)
    REFERENCES `mydb`.`classify_level1` (`classify1_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brandID` INT NOT NULL,
  `brandname` VARCHAR(45) NULL,
  PRIMARY KEY (`brandID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`product` - 修复版本
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `classify_level1_classify1_ID` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_baozhiqi` INT NULL COMMENT '保质期（月），可为空，支持无保质期商品',
  `local` VARCHAR(45) NULL,
  `brand_brandID` INT NOT NULL,
  `product_details` TEXT NULL COMMENT '商品详情',
  `cover_image` VARCHAR(500) NULL DEFAULT NULL COMMENT '商品封面图片，可为空',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`productID`),
  INDEX `fk_product_classify_level11_idx` (`classify_level1_classify1_ID` ASC) VISIBLE,
  INDEX `fk_product_brand1_idx` (`brand_brandID` ASC) VISIBLE,
  INDEX `idx_product_name` (`product_name` ASC) VISIBLE,
  INDEX `idx_product_created` (`created_at` ASC) VISIBLE,
  CONSTRAINT `fk_product_classify_level11`
    FOREIGN KEY (`classify_level1_classify1_ID`)
    REFERENCES `mydb`.`classify_level1` (`classify1_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `mydb`.`brand` (`brandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`spec_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spec_type` (
  `spec_type_id` INT NOT NULL AUTO_INCREMENT,
  `spec_name` VARCHAR(45) NOT NULL COMMENT '规格名称，如：重量、尺寸、颜色等',
  `unit` VARCHAR(20) NULL COMMENT '单位，如：kg、g、ml、L、cm、mm等',
  `description` TEXT NULL COMMENT '规格描述',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否启用',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`spec_type_id`),
  UNIQUE INDEX `spec_name_UNIQUE` (`spec_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`spec` - 修复版本
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spec` (
  `specID` INT NOT NULL,
  `product_productID` INT NOT NULL,
  `spec_type_id` INT NULL COMMENT '规格类型ID，关联spec_type表，可为空',
  `spec_name` VARCHAR(45) NULL COMMENT '规格名称，可为空',
  `spec_value` VARCHAR(45) NULL COMMENT '规格值，可为空',
  `barcode` VARCHAR(50) NULL COMMENT '条形码，VARCHAR类型，可为空，支持同一商品不同规格使用相同条形码',
  `picture` VARCHAR(500) NULL COMMENT '规格图片，可为空',
  `总库存` INT NULL DEFAULT 0 COMMENT '总库存，可为空，默认为0',
  `unit` VARCHAR(20) NULL COMMENT '单位，可为空',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`specID`),
  INDEX `fk_spec_detail_product1_idx` (`product_productID` ASC) VISIBLE,
  INDEX `fk_spec_spec_type_idx` (`spec_type_id` ASC) VISIBLE,
  INDEX `idx_spec_product_id` (`product_productID` ASC) VISIBLE,
  INDEX `idx_spec_barcode` (`barcode` ASC) VISIBLE,
  INDEX `idx_spec_created` (`created_at` ASC) VISIBLE,
  -- 移除条形码唯一约束，允许同一商品的不同规格使用相同条形码
  CONSTRAINT `fk_spec_detail_product1`
    FOREIGN KEY (`product_productID`)
    REFERENCES `mydb`.`product` (`productID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_spec_spec_type`
    FOREIGN KEY (`spec_type_id`)
    REFERENCES `mydb`.`spec_type` (`spec_type_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dealer` (
  `dealerID` INT NOT NULL,
  `dealer_name` VARCHAR(45) NULL,
  `dealer_tel` VARCHAR(20) NULL,
  `dealer_address` VARCHAR(45) NULL,
  PRIMARY KEY (`dealerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`stock_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_in` (
  `stock_inID` INT NOT NULL AUTO_INCREMENT,
  `stock_in_date` DATETIME NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `dealer_dealerID` INT NOT NULL,
  PRIMARY KEY (`stock_inID`),
  INDEX `fk_stock_in_dealer1_idx` (`dealer_dealerID` ASC) VISIBLE,
  CONSTRAINT `fk_stock_in_dealer1`
    FOREIGN KEY (`dealer_dealerID`)
    REFERENCES `mydb`.`dealer` (`dealerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`stock_in_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_in_detail` (
  `stock_in_detail` INT NOT NULL,
  `stock_inID` INT NOT NULL,
  `spec_specID` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price_in` DECIMAL(10,2) NOT NULL,
  `product_date` DATE NOT NULL,
  PRIMARY KEY (`stock_in_detail`),
  INDEX `fk_stock_in_detail_stock_in1_idx` (`stock_inID` ASC) VISIBLE,
  INDEX `fk_stock_in_detail_spec1_idx` (`spec_specID` ASC) VISIBLE,
  CONSTRAINT `fk_stock_in_detail_stock_in1`
    FOREIGN KEY (`stock_inID`)
    REFERENCES `mydb`.`stock_in` (`stock_inID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_in_detail_spec1`
    FOREIGN KEY (`spec_specID`)
    REFERENCES `mydb`.`spec` (`specID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`brand_has_dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand_has_dealer` (
  `brand_brandID` INT NOT NULL,
  `dealer_dealerID` INT NOT NULL,
  PRIMARY KEY (`brand_brandID`, `dealer_dealerID`),
  INDEX `fk_brand_has_dealer_dealer1_idx` (`dealer_dealerID` ASC) VISIBLE,
  INDEX `fk_brand_has_dealer_brand1_idx` (`brand_brandID` ASC) VISIBLE,
  CONSTRAINT `fk_brand_has_dealer_brand1`
    FOREIGN KEY (`brand_brandID`)
    REFERENCES `mydb`.`brand` (`brandID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_brand_has_dealer_dealer1`
    FOREIGN KEY (`dealer_dealerID`)
    REFERENCES `mydb`.`dealer` (`dealerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `price` DECIMAL(10,2) NULL,
  `discount` DECIMAL(10,2) NULL,
  `sale_time` DATETIME NULL,
  `pay_way` VARCHAR(45) NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_order_customers1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`order_deatil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_deatil` (
  `order_deatilID` INT NOT NULL AUTO_INCREMENT,
  `order_orderID` INT NOT NULL,
  `spec_specID` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_deatilID`, `order_orderID`),
  INDEX `fk_order_deatil_order1_idx` (`order_orderID` ASC) VISIBLE,
  INDEX `fk_order_deatil_spec1_idx` (`spec_specID` ASC) VISIBLE,
  CONSTRAINT `fk_order_deatil_order1`
    FOREIGN KEY (`order_orderID`)
    REFERENCES `mydb`.`order` (`orderID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_deatil_spec1`
    FOREIGN KEY (`spec_specID`)
    REFERENCES `mydb`.`spec` (`specID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `duration` INT NOT NULL COMMENT '分钟',
  `price` DECIMAL(10,2) NOT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mydb`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`appointments` (
  `appointment_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `pet_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `appointment_date` DATE NOT NULL,
  `appointment_time` TIME NOT NULL,
  `status` ENUM('待确认', '已确认', '已完成', '已取消') NOT NULL DEFAULT '待确认',
  `notes` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`appointment_id`),
  INDEX `fk_appointments_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_appointments_pet_idx` (`pet_id` ASC) VISIBLE,
  INDEX `fk_appointments_service_idx` (`service_id` ASC) VISIBLE,
  INDEX `idx_appointment_date` (`appointment_date` ASC) VISIBLE,
  INDEX `idx_appointment_status` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_appointments_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_appointments_pet`
    FOREIGN KEY (`pet_id`)
    REFERENCES `mydb`.`pets` (`pet_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_appointments_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`service_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- 插入默认数据
-- -----------------------------------------------------

-- 插入默认规格类型
INSERT IGNORE INTO `spec_type` (`spec_type_id`, `spec_name`, `unit`, `description`, `is_active`) VALUES 
(1, '默认规格', '', '系统默认规格类型', TRUE),
(2, '颜色', '', '颜色规格', TRUE),
(3, '尺寸', 'cm', '尺寸规格', TRUE),
(4, '重量', 'g', '重量规格', TRUE),
(5, '容量', 'ml', '容量规格', TRUE);

-- 插入示例品牌数据
INSERT IGNORE INTO `brand` (`brandID`, `brandname`) VALUES 
(1, '示例品牌1'),
(2, '示例品牌2'),
(3, '示例品牌3'),
(4, '皇家'),
(5, '希尔斯'),
(6, '冠能');

-- 插入示例分类数据
INSERT IGNORE INTO `classify_level1` (`classify1_ID`, `name`, `parentID`) VALUES 
(1, '宠物用品', NULL),
(2, '食品', 1),
(3, '玩具', 1),
(4, '护理用品', 1),
(5, '狗粮', 2),
(6, '猫粮', 2),
(7, '狗玩具', 3),
(8, '猫玩具', 3);

-- 插入示例经销商数据
INSERT IGNORE INTO `dealer` (`dealerID`, `dealer_name`, `dealer_tel`, `dealer_address`) VALUES 
(1, '示例经销商1', '1234567890', '示例地址1'),
(2, '示例经销商2', '1234567891', '示例地址2'),
(3, '宠物用品批发商', '13800138000', '北京市朝阳区'),
(4, '宠物食品供应商', '13900139000', '上海市浦东区');

-- 插入示例服务数据
INSERT IGNORE INTO `services` (`service_id`, `service_name`, `description`, `duration`, `price`, `is_active`) VALUES 
(1, '基础洗澡', '宠物基础洗澡服务', 60, 50.00, TRUE),
(2, '美容修剪', '宠物美容修剪服务', 90, 80.00, TRUE),
(3, '健康检查', '宠物健康检查服务', 30, 30.00, TRUE),
(4, '疫苗接种', '宠物疫苗接种服务', 20, 100.00, TRUE);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
